---
name: "Update Modules base"

on:
  workflow_dispatch:

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  update-Modules:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
        env:
          COMMIT_NAME: ${{ steps.app-token.outputs.app-slug }}[bot] 
          COMMIT_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com

      - name: Clone Firmware
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Configure Git User and E-Mail
        run: git config --global user.name "${{ env.COMMIT_NAME }}" && git config --global user.email "${{ env.COMMIT_EMAIL }}"
        
      - name: Get update branch name
        id: branch-name
        run: echo "branch-name=update-modules-${{ github.ref_name }}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Invoke update-modules
        run: ./contrib/actions/update-modules.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: '[${{ github.ref_name }}] update modules'
          body: |
            Update modules for ${{ github.ref_name }} branch
            <sub><sup>- Auto-generated by [create-pull-request][1]</sub></sup>

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ${{ steps.branch-name.outputs.branch-name }}
          labels: ${{ github.ref_name }}
          draft: true # this step does not trigger a CI run, so always mark them as draft
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
